# config/packages/cache.yaml
framework:
    cache:
        prefix_seed: eve_tools

        app: cache.adapter.redis

        default_redis_provider: '%env(REDIS_URL)%'

        pools:
            doctrine.result_cache_pool:
                adapter: cache.adapter.redis
            doctrine.system_cache_pool:
                adapter: cache.adapter.system
            esi.cache:
                adapter: cache.adapter.redis
                default_lifetime: 300
            jwt.blacklist:
                adapter: cache.adapter.redis
                default_lifetime: 3700
            structure_market.cache:
                adapter: cache.adapter.redis
                default_lifetime: 7200  # 2 hours

when@test:
    framework:
        cache:
            app: cache.adapter.array
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.adapter.array
                doctrine.system_cache_pool:
                    adapter: cache.adapter.array
                esi.cache:
                    adapter: cache.adapter.array
                jwt.blacklist:
                    adapter: cache.adapter.array
                structure_market.cache:
                    adapter: cache.adapter.array
