# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/.well-known/mercure':
            allow_origin: ['*']
            allow_headers: ['Authorization', 'Last-Event-ID', 'Cache-Control']
            expose_headers: ['Link', 'X-Mercure-Updates']
        '^/': null
